### ISSUE TITLE
您好!请问您使用的mmcv是哪个版本？

### ISSUE THREAD

**Issue by Billy-ZTB** [qyan0131/FDLNet#1]
我的环境里没有mmcv.runner 
![image](https://github.com/qyan0131/FDLNet/assets/52749583/8fa83ebb-3a74-4f13-8934-be44d01bc5ab)
我是这个版本：
![image](https://github.com/qyan0131/FDLNet/assets/52749583/3a8a0e58-ed5b-42a0-8e68-d38021fc14b4)

**Comment by qyan0131** [comment]
Hi,

Thanks for your interest in our work.

I think you might be using the mismatch version of MMSegmentation, as well as MMCV.

As mentioned in the README, we are using the 0.x branch of MMSegmentation (NOT the default main branch, e.g., 2.1.0 in your case) with MMCV-full<2.0.0. Please follow the steps in the README to configure and install the environment.

Best

**Comment by Billy-ZTB** [comment]
Thanks, I've found the right version and solved this problem.

**Comment by Billy-ZTB** [comment]
Hello! I have another question to ask. After I read the fdlnet.py, I found that class DToS wasn't used. It seems like the image is cut into 8*8 patches but never transferred back. Did I miss something? Looking forward to your reply!

**Comment by Billy-ZTB** [comment]
@qyan0131  I am also curious about how the pictures were generated in Fig3.  When I remove some of the high frequency part of the image by fft and ifft, the image gets blurred, not like the picture in your papar, which still contains explicit contour of those objects.
